server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 9091

logging:
  level: INFO
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout
    - type: file
      threshold: ALL
      currentLogFilename: ./log/karamel.log
      archivedLogFilenamePattern: ./log/karamel-%d.log.gz,
      archivedFileCount: 5
      timeZone: UTC

name: Karamel-Webservice
